# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testnbdev',
                'doc_host': 'https://ruxkor.github.io',
                'git_url': 'https://github.com/ruxkor/testnbdev',
                'lib_path': 'testnbdev'},
  'syms': {'testnbdev.core': {'testnbdev.core.foo': ('core.html#foo', 'testnbdev/core.py')}}}
